'use client';

import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { BarChart3, Check, Database, FileSpreadsheet, LogIn, Plus, Save, Send, Sparkles, User } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/components/auth/auth-provider';
import { getReportTable, stripTotalsRow } from '@/lib/dashboard/report-table';
import { getChartSpec, type ChartSpec } from '@/lib/dashboard/chart-spec';
import { AutoReportChart } from '@/components/dashboard/charts/auto-report-chart';
import { ChartErrorBoundary } from '@/components/dashboard/charts/chart-error-boundary';
import { XLSX_MIME_TYPE, base64ToBlob, buildXlsxBase64, triggerDownload } from '@/lib/download';
import type { ChatResponse, DashboardData } from '@/lib/dashboard/metrics';

type Message = {
  role: 'user' | 'assistant';
  text: string;
  tablesUsed?: string[];
  // A report generated by THIS turn, rendered inline right below this
  // message and never touched again by a later turn -- see the removal of
  // the old single global `artifact` state further down for why.
  artifact?: Artifact;
  reportSaveState?: 'idle' | 'saving' | 'saved' | 'error';
  tableExpanded?: boolean;
  // A chart-type/measure edit made to this message's OWN inline chart in
  // the chat panel -- captured here (instead of being pure local state
  // inside ReportBlock/AutoReportChart) so Save Report can persist the
  // exact chart the user is looking at, not always the auto-picked
  // default. Undefined means "use the auto-picked default."
  chartSpecOverride?: ChartSpec;
  // When this message was sent/received -- an ISO string. Hydrated
  // messages get the real `created_at` the DB stored; a message just sent
  // this session is stamped client-side at push time (it's saved to the
  // DB a moment later, but the chat should show a time immediately, not
  // wait on that round trip).
  createdAt?: string;
};

type Artifact = {
  title: string;
  narrative: string;
  topic: string;
  chartType: 'bar' | 'line' | 'pie' | 'donut' | 'none';
  data: DashboardData;
  days: number;
  region: string | null;
  tablesUsed: string[];
};

const WELCOME_MESSAGE: Message = {
  role: 'assistant',
  text: 'Hi. Ask about billing, collections, POPs, active customers, or support tickets, or request a report.',
};

// A time under every message, so scrolling back through a long
// conversation actually tells you when each turn happened, not just their
// order. Same-day messages show just the time; anything older also shows
// the date, since "3:45 PM" alone is ambiguous a week later.
function formatMessageTime(iso?: string): string | null {
  if (!iso) return null;
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return null;
  const now = new Date();
  const isToday =
    date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth() && date.getDate() === now.getDate();
  const time = date.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
  if (isToday) return time;
  const day = date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
  return `${day}, ${time}`;
}

async function saveMessage(
  sessionId: number,
  role: 'user' | 'assistant',
  text: string,
  tablesUsed?: string[],
  // The report this specific message generated, if any -- persisted
  // verbatim so reopening this conversation later can render the exact
  // same table/chart again instead of just the plain text (see the
  // report_data column added to chat_messages).
  reportData?: Artifact,
) {
  try {
    await fetch('/api/chat-history', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sessionId, role, content: text, tablesUsed, reportData }),
    });
  } catch {
    // Best-effort persistence -- a failed save should never block the chat UI.
  }
}

// Saving is a deliberate, user-initiated action (the "Save Report" button
// in the report panel) -- it never happens automatically just because a
// chart was generated, so the Reports list only fills up with reports the
// user actually chose to keep.
// chartSpec here is the auto-picked default (see getChartSpec at the top
// of ChatWorkspace) -- the chat panel's own chart edits are session-only
// by design (they reset each question, see the ChartErrorBoundary's own
// per-message key), so Save always stores the default, sensible chart.
// Editing a chart's type/measures/row-count PERSISTENTLY happens on the
// saved report page instead, where AutoReportChart is given onSpecChange
// and a real Save-chart action.
async function saveReport(artifact: Artifact, chartSpec: unknown): Promise<boolean> {
  try {
    const response = await fetch('/api/reports', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        title: artifact.title,
        narrative: artifact.narrative,
        topic: artifact.topic,
        chartType: artifact.chartType,
        filters: { days: artifact.days, region: artifact.region },
        tablesUsed: artifact.tablesUsed,
        data: artifact.data,
        chartSpec,
      }),
    });
    return response.ok;
  } catch {
    return false;
  }
}

export function ChatWorkspace({ initialData = null }: { initialData?: DashboardData | null }) {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();
  const requestedSessionId = searchParams.get('session');

  // FIX 2026-09-17: previously the ONLY source of this data was the
  // `initialData` prop, fetched server-side in app/chat/page.tsx BEFORE the
  // page was allowed to render at all -- see that file's comment. Fetched
  // here instead, after mount, so it never blocks the chat UI itself from
  // appearing; it's only read later, when a message is actually sent (see
  // activeData below), by which point this same-origin fetch has almost
  // always already resolved.
  const [homeData, setHomeData] = useState<DashboardData | null>(initialData);
  useEffect(() => {
    if (homeData) return;
    let cancelled = false;
    // PERF FIX 2026-09-17: this only ever feeds kpi labels + static
    // chartSources + top-POP context (see activeData usage below) -- it
    // never needed package/customer/ticket/transaction-mode breakdowns.
    // topic=pops keeps that context real while skipping the full
    // 386k-customer aggregation and every other breakdown this page never
    // renders (see readonly-api.mjs/dashboard-data.mjs's own comments).
    fetch('/api/dashboard-data?topic=pops')
      .then((res) => (res.ok ? res.json() : null))
      .then((data: DashboardData | null) => {
        if (!cancelled && data) setHomeData(data);
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  // FIX 2026-09-15: the loading bubble below used to say the same fixed
  // sentence no matter how long a turn actually took -- a real compound
  // question (two metrics, a wide POP range) can genuinely take up to the
  // backend's own ~90s timeout (see readonly-api.mjs), and with no signal
  // that it was still working, that looked identical to "frozen/broken".
  // This escalates the message after 8s so a slow-but-working turn reads
  // as slow, not dead.
  const [slowRequest, setSlowRequest] = useState(false);
  const slowRequestTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [messages, setMessages] = useState<Message[]>([WELCOME_MESSAGE]);
  const [sessionId, setSessionId] = useState<number | null>(null);
  const [sessionTitle, setSessionTitle] = useState<string | null>(null);
  const sessionSetupRef = useRef<string | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  function updateMessage(index: number, patch: Partial<Message>) {
    setMessages((prev) => prev.map((m, i) => (i === index ? { ...m, ...patch } : m)));
  }

  function toggleTableExpanded(index: number) {
    setMessages((prev) => prev.map((m, i) => (i === index ? { ...m, tableExpanded: !m.tableExpanded } : m)));
  }

  // Most-recently-generated report still in the scrollback, if any -- used
  // only to seed the cosmetic page_state context sent with the next
  // message (see activeData usage below), same role the single global
  // `artifact` used to play.
  const lastArtifact = [...messages].reverse().find((m) => m.artifact)?.artifact;
  const activeData = lastArtifact?.data ?? homeData;

  useEffect(() => {
    if (authLoading || !user || !requestedSessionId) return;
    const setupKey = `${user.id}:${requestedSessionId}`;
    if (sessionSetupRef.current === setupKey) return;
    sessionSetupRef.current = setupKey;

    fetch(`/api/chat-sessions/${requestedSessionId}`)
      .then((res) => res.json())
      .then((body: { session: { id: number; title: string } | null; messages: Array<{ role: 'user' | 'assistant'; content: string; tables_used: string[] | null; report_data: Artifact | null; created_at: string }> }) => {
        if (!body.session) return;
        setSessionId(body.session.id);
        setSessionTitle(body.session.title);
        if (body.messages.length) {
          setMessages(
            body.messages.map((m) => ({
              role: m.role,
              text: m.content,
              tablesUsed: m.tables_used ?? undefined,
              // Restores the report that generated this message, if one was
              // saved for it -- reopening a conversation now shows the same
              // tables/charts it had originally while scrolling, not just
              // text. Undefined for a plain answer, or a message saved
              // before this column existed.
              artifact: (m.report_data as Artifact | null | undefined) ?? undefined,
              reportSaveState: m.report_data ? 'idle' : undefined,
              tableExpanded: false,
              createdAt: m.created_at,
            })),
          );
        }
      })
      .catch(() => {});
  }, [authLoading, user, requestedSessionId]);

  async function ensureSession(firstMessage: string): Promise<number | null> {
    if (!user) return null;
    if (sessionId) return sessionId;
    try {
      const res = await fetch('/api/chat-sessions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title: firstMessage.slice(0, 80) }),
      });
      const body = (await res.json()) as { id: number; title: string };
      setSessionId(body.id);
      setSessionTitle(body.title);
      router.replace(`/chat?session=${body.id}`, { scroll: false });
      return body.id;
    } catch {
      return null;
    }
  }

  // Only auto-scroll for an actual new turn (a message was appended) or
  // the loading indicator appearing/disappearing -- NOT for every
  // `messages` change. An in-place edit to an existing message (e.g. the
  // user switching a chart's type/measure inline, which calls
  // updateMessage on the SAME message count) must never yank the scroll
  // position out from under them while they're still looking at it.
  const prevMessageCountRef = useRef(messages.length);
  useEffect(() => {
    const grew = messages.length > prevMessageCountRef.current;
    prevMessageCountRef.current = messages.length;
    if (!grew && !loading) return;
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: 'smooth' });
  }, [messages, loading]);

  function handleNewChat() {
    setMessages([WELCOME_MESSAGE]);
    setSessionId(null);
    setSessionTitle(null);
    sessionSetupRef.current = null;
    router.push('/chat');
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const message = input.trim();
    if (!message || loading) return;

    setInput('');
    setLoading(true);
    setSlowRequest(false);
    if (slowRequestTimerRef.current) clearTimeout(slowRequestTimerRef.current);
    slowRequestTimerRef.current = setTimeout(() => setSlowRequest(true), 8_000);
    // Captured BEFORE this turn's own message is appended -- "was a report
    // already open going into this turn" is what lets a plain correction
    // ("i meant Europe") that never says the word report/chart still
    // refresh the inline report instead of only a create_new_page turn
    // being allowed to. See the result-handling block below.
    const hadOpenReport = messages.some((m) => m.artifact);
    // Captured before ensureSession -- true only when this send is the one
    // that creates a brand-new chat_sessions row (New chat -> first
    // message). Used below to tell the sidebar's Recent Chats list to
    // pick up the new conversation once it's actually saved, instead of
    // only ever appearing there after a full page reload.
    const wasNewSession = !sessionId;
    setMessages((prev) => [...prev, { role: 'user', text: message, createdAt: new Date().toISOString() }]);
    const activeSessionId = await ensureSession(message);
    if (user && activeSessionId) {
      saveMessage(activeSessionId, 'user', message);
    }

    try {
      // Goes through this app's own /api/chat route, not the internal
      // backend directly -- that route enforces sign-in and rate limiting
      // before it ever reaches the backend. See app/api/chat/route.ts.
      const response = await fetch(
        '/api/chat',
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            message,
            history: messages.slice(-12).map((m) => ({ role: m.role, content: m.text })),
            page_state: {
              page: 'chat',
              days: lastArtifact?.days ?? 30,
              region: lastArtifact?.region ?? null,
              kpis: activeData?.kpis?.map((kpi) => kpi.label) ?? [],
              chartSources: activeData?.chartSources ?? null,
            },
          }),
        },
      );

      if (!response.ok) {
        const body = await response.text();
        // The API returns { error: "..." } as JSON -- surface that message
        // directly instead of the raw JSON blob when we can parse it.
        let message = body || 'Chat request failed';
        try {
          const parsed = JSON.parse(body) as { error?: string };
          if (parsed.error) message = parsed.error;
        } catch {
          // body wasn't JSON -- fall back to the raw text above.
        }
        throw new Error(message);
      }

      const result = (await response.json()) as ChatResponse;
      // A turn can come back with real, freshly-queried breakdown data even
      // when the report gate didn't call this a "create a report" request --
      // e.g. a correction like "i meant X" that answers a question about a
      // report already on screen, without using the word report/chart. In
      // that case this turn's own message still gets its own fresh inline
      // report (never the earlier one silently rewritten in place) so the
      // scrollback keeps showing exactly what each turn actually produced.
      // A clarifying question means NOTHING was actually looked up this
      // turn (FIX 2026-09-17), so it never attaches a report of its own --
      // this message just carries the question, same as any plain reply.
      const newArtifact: Artifact | undefined =
        !result.askedClarification && result.data && (result.intent === 'create_new_page' || hadOpenReport)
          ? {
              title: result.title,
              narrative: result.narrative,
              topic: result.topic ?? 'dashboard',
              chartType: result.chartType ?? 'bar',
              data: result.data,
              days: result.filters.days,
              region: result.filters.region,
              tablesUsed: result.tablesUsed,
            }
          : undefined;
      setMessages((prev) => [
        ...prev,
        {
          role: 'assistant',
          text: result.narrative,
          tablesUsed: result.tablesUsed,
          artifact: newArtifact,
          reportSaveState: newArtifact ? 'idle' : undefined,
          tableExpanded: false,
          createdAt: new Date().toISOString(),
        },
      ]);
      if (user && activeSessionId) saveMessage(activeSessionId, 'assistant', result.narrative, result.tablesUsed, newArtifact);
      // A brand-new chat's first exchange is done and saved (including
      // the auto-title-from-first-message update /api/chat-history makes
      // server-side) -- tell the sidebar's Recent Chats list to refresh so
      // this conversation shows up there right away, without the user
      // having to reload the page or navigate away and back.
      if (wasNewSession && activeSessionId) {
        window.dispatchEvent(new Event('bi:chat-session-created'));
      }
    } catch (error) {
      const errorText =
        error instanceof Error
          ? `I could not complete that request: ${error.message}`
          : 'I could not complete that request.';
      setMessages((prev) => [...prev, { role: 'assistant', text: errorText, createdAt: new Date().toISOString() }]);
    } finally {
      if (slowRequestTimerRef.current) {
        clearTimeout(slowRequestTimerRef.current);
        slowRequestTimerRef.current = null;
      }
      setLoading(false);
      setSlowRequest(false);
    }
  }

  async function handleSaveReport(index: number) {
    const message = messages[index];
    const target = message?.artifact;
    if (!target || !user) return;
    updateMessage(index, { reportSaveState: 'saving' });
    // If the user edited this message's chart (type/measure/row-count) in
    // the chat panel itself, that edit is what gets saved -- otherwise
    // fall back to recomputing the same auto-picked default ReportBlock
    // renders from, so Save never disagrees with what's on screen.
    let spec: ReturnType<typeof getChartSpec> = message?.chartSpecOverride ?? { groups: [] };
    if (!message?.chartSpecOverride) {
      const table = getReportTable(target.topic, target.data, target.chartType);
      try {
        spec = getChartSpec({ headers: table.headers, rows: stripTotalsRow(table) });
      } catch {
        // A chart-spec failure shouldn't block saving the report itself --
        // ReportBlock already surfaces this loudly in the UI.
      }
    }
    const ok = await saveReport(target, spec);
    updateMessage(index, { reportSaveState: ok ? 'saved' : 'error' });
  }

  async function handleExportArtifact(index: number) {
    const artifact = messages[index]?.artifact;
    if (!artifact) return;
    const table = getReportTable(artifact.topic, artifact.data, artifact.chartType);
    const fileName = `${artifact.title.toLowerCase().replace(/\s+/g, '-')}.xlsx`;
    const base64 = buildXlsxBase64(table.headers, table.rows);
    triggerDownload(fileName, base64ToBlob(base64, XLSX_MIME_TYPE));
    // FIX 2026-09-19: this used to only trigger the browser download --
    // the /exports page (and its own empty-state copy: "click Export Excel
    // ... it will show up here") reads from the report_exports table via
    // POST /api/exports, and nothing here ever called it, so an export
    // from the chat panel's inline artifact (as opposed to a saved report
    // page, which already did this correctly via reports/[id]/page.tsx's
    // own logExport) never appeared in Exports. reportId is null here
    // since this artifact may not be a saved report yet -- the exports
    // table already allows that (see report_exports schema).
    if (!user) return;
    try {
      const res = await fetch('/api/exports', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reportId: null, fileName, format: 'xlsx', fileContent: base64 }),
      });
      if (!res.ok) {
        const text = await res.text();
        console.error('Saving to export history failed:', res.status, text);
      }
    } catch (error) {
      console.error('Saving to export history failed:', error);
    }
  }

  return (
    <div className="flex h-full min-h-0 flex-col overflow-hidden rounded-2xl border border-white/70 bg-white/90 shadow-[0_6px_18px_rgb(15_23_42/9%)] ring-1 ring-slate-950/5 backdrop-blur">
      <div className="shrink-0 border-b border-slate-200/70 bg-white/70 px-5 py-4">
        <div className="flex items-center justify-between gap-4">
          <div className="min-w-0">
            <h2 className="truncate text-base font-bold">
              {sessionTitle && sessionTitle !== 'New conversation' ? sessionTitle : 'Conversation'}
            </h2>
            <p className="text-sm text-slate-500">Ask a question, or ask for a report or graph.</p>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            {user ? (
              <Button variant="outline" size="sm" className="gap-1.5" onClick={handleNewChat}>
                <Plus size={14} />
                New chat
              </Button>
            ) : !authLoading ? (
              <Link
                href="/login"
                className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold text-slate-600 shadow-sm transition hover:border-blue-200 hover:text-blue-700"
              >
                <LogIn size={12} />
                Sign in to save history
              </Link>
            ) : null}
          </div>
        </div>
      </div>

      {/* The one scroll region for the whole workspace -- a report/chart a
          past turn generated renders full-width right below that turn's
          own message and scrolls with it, instead of living in a separate
          side panel that only ever showed the LATEST one. Scrolling back
          up through the conversation shows every report exactly as it
          looked when it was generated. */}
      <div ref={scrollRef} className="min-h-0 flex-1 space-y-5 overflow-auto bg-gradient-to-b from-slate-50/70 to-white p-5">
        {messages.map((message, index) =>
          message.role === 'user' ? (
            <div key={`${message.role}-${index}`} className="flex flex-col items-end gap-1">
              {/* FIX: dropped the max-w-76% + ml-auto wrapper entirely --
                  that put a SEPARATE width-constrained box between this
                  row and the true container edge, and relied on that
                  box's own right edge coinciding with the container's
                  right edge (correct in theory, but one more layer that
                  can be undermined by any later change). This row is now
                  the same full-width row the assistant's reply uses --
                  no intermediate box, nothing to ever get out of sync.
                  The bubble itself still isn't full-width (it has no
                  width class, so it sizes to its own text, same as
                  before) -- only the ROW is full-width, and justify-end
                  packs the bubble+icon flush against that row's true
                  right edge, which is now, structurally, the exact same
                  coordinate the assistant content ends at. */}
              <div className="flex w-full items-start justify-end gap-3">
                <div className="rounded-2xl rounded-tr-md bg-gradient-to-br from-blue-600 to-indigo-600 px-4 py-3 text-sm font-medium leading-6 text-white shadow-lg shadow-blue-600/20">
                  {message.text}
                </div>
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-slate-700 to-slate-900 text-white shadow-md">
                  <User size={16} />
                </div>
              </div>
              {formatMessageTime(message.createdAt) ? (
                <p className="mr-12 text-[11px] text-slate-400">{formatMessageTime(message.createdAt)}</p>
              ) : null}
            </div>
          ) : (
            <div key={`${message.role}-${index}`} className="space-y-3">
              {/* mr-12 (48px) is the exact same fixed right margin the
                  report card below uses -- a percentage cap still let a
                  long reply crowd the edge, so both now stop the same
                  fixed distance short of the row's right edge no matter
                  how much text there is. */}
              <div className="flex w-full max-w-full items-start gap-3">
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-950 text-white shadow-md">
                  <Sparkles size={16} />
                </div>
                <div className="min-w-0 flex-1 mr-12">
                <div className="min-w-0 max-w-full rounded-2xl rounded-tl-md border border-white/70 bg-white/90 px-4 py-3 text-sm leading-6 text-slate-700 shadow-[0_4px_14px_rgb(15_23_42/7%)] ring-1 ring-slate-950/5 backdrop-blur">
                  <p className="whitespace-pre-line break-words">{message.text}</p>
                  {Array.isArray(message.tablesUsed) && message.tablesUsed.length > 0 ? (
                    <div className="mt-2 flex flex-wrap items-center gap-1.5 border-t border-slate-100 pt-2">
                      <Database size={12} className="text-slate-400" />
                      <span className="text-[11px] font-medium uppercase tracking-wide text-slate-400">
                        Tables used:
                      </span>
                      {message.tablesUsed.map((table) => (
                        <span
                          key={table}
                          className="rounded-md border border-slate-200 bg-slate-50 px-1.5 py-0.5 text-[11px] font-medium text-slate-600"
                        >
                          {table}
                        </span>
                      ))}
                    </div>
                  ) : null}
                </div>
                {formatMessageTime(message.createdAt) ? (
                  <p className="mt-1 ml-1 text-[11px] text-slate-400">{formatMessageTime(message.createdAt)}</p>
                ) : null}
                </div>
              </div>

              {message.artifact ? (
                // Same left inset as the bubble above (avatar width + the
                // row's own gap-3 -- h-9 avatar is 36px, gap-3 is 12px,
                // ml-12 is 48px, so this lines up exactly under the text,
                // not under the avatar icon itself). mr-12 mirrors that on
                // the right, so the report card leaves the same gap before
                // the row's right edge that the capped reply bubble does,
                // instead of stretching out further than the text above it.
                <div className="ml-12 mr-12">
                  <ChartErrorBoundary key={`chart-${index}`}>
                    <ReportBlock
                      artifact={message.artifact}
                      user={!!user}
                      reportSaveState={message.reportSaveState ?? 'idle'}
                      tableExpanded={!!message.tableExpanded}
                      chartSpecOverride={message.chartSpecOverride ?? null}
                      onSave={() => handleSaveReport(index)}
                      onExport={() => handleExportArtifact(index)}
                      onToggleExpand={() => toggleTableExpanded(index)}
                      onSpecChange={(spec) => updateMessage(index, { chartSpecOverride: spec })}
                    />
                  </ChartErrorBoundary>
                </div>
              ) : null}
            </div>
          ),
        )}
        {loading ? (
          <div className="flex max-w-[76%] items-start gap-3">
            <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-slate-950 text-white shadow-md">
              <Sparkles size={16} />
            </div>
            <div className="rounded-2xl rounded-tl-md border border-white/70 bg-white/90 px-4 py-3 text-sm leading-6 text-slate-500 shadow-[0_4px_14px_rgb(15_23_42/7%)] ring-1 ring-slate-950/5 backdrop-blur">
              {slowRequest
                ? 'Still working -- this question needs more than one real database lookup, so it is taking longer than usual (up to ~90s for a heavy or multi-part question).'
                : 'Reading the database and preparing a grounded answer...'}
            </div>
          </div>
        ) : null}
      </div>

      <form onSubmit={handleSubmit} className="shrink-0 border-t border-slate-200/80 bg-white/90 p-4">
        <div className="flex items-end gap-3 rounded-2xl border border-indigo-200 bg-white p-3 shadow-[0_14px_34px_rgb(79_70_229/14%)] ring-4 ring-indigo-50">
          <textarea
            value={input}
            onChange={(event) => setInput(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === 'Enter' && !event.shiftKey) {
                event.preventDefault();
                event.currentTarget.form?.requestSubmit();
              }
            }}
            className="max-h-32 min-h-16 flex-1 resize-none bg-transparent text-sm leading-6 text-slate-900 outline-none placeholder:text-slate-400"
            placeholder="Ask anything about billing, collections, POPs, or tickets..."
          />
          <Button
            type="submit"
            disabled={loading || !input.trim()}
            className="h-11 gap-2 rounded-xl bg-gradient-to-br from-indigo-600 to-violet-600 px-5 font-semibold shadow-lg shadow-indigo-600/25 hover:from-indigo-700 hover:to-violet-700"
          >
            <Send size={16} />
            {loading ? 'Working' : 'Ask'}
          </Button>
        </div>
      </form>
    </div>
  );
}

// One turn's generated report, rendered inline right below that turn's own
// message -- title/narrative, the Save/Export/Saved-Reports actions, the
// row-limited table preview, and the chart, all together in the single
// block that used to be split across a side panel (title/narrative/table)
// and a separate full-width section below it (the chart). Every field it
// needs (chartSpec, the table, the chart's own row data) is recomputed
// fresh from `artifact` -- the same deterministic table-building/chart-spec
// functions the rest of the app uses -- so it can never disagree with what
// was actually looked up for this turn.
function ReportBlock({
  artifact,
  user,
  reportSaveState,
  tableExpanded,
  chartSpecOverride,
  onSave,
  onExport,
  onToggleExpand,
  onSpecChange,
}: {
  artifact: Artifact;
  user: boolean;
  reportSaveState: 'idle' | 'saving' | 'saved' | 'error';
  tableExpanded: boolean;
  chartSpecOverride: ChartSpec | null;
  onSave: () => void;
  onExport: () => void;
  onToggleExpand: () => void;
  onSpecChange: (spec: ChartSpec) => void;
}) {
  const inlineTable = getReportTable(artifact.topic, artifact.data, artifact.chartType);
  // Chart is generated from the SAME table data, minus the Totals row (a
  // chart bar for "Total (N rows)" would be meaningless) -- so the chart
  // and the table it sits below can never disagree.
  const chartRows = stripTotalsRow(inlineTable);
  // FIX: getChartSpec (and, if this ever throws, whatever's downstream of
  // it) used to be able to fail SILENTLY -- an uncaught error in this
  // computation just meant the whole chart section quietly never
  // appeared, with nothing in the UI to say why, and nothing for us to go
  // on when a report's chart didn't show up. This makes a failure LOUD
  // instead: the real error is logged to the console (open devtools ->
  // Console to see it) and a visible message replaces the missing chart,
  // instead of the report looking like it just silently skipped charting.
  let chartSpec: ReturnType<typeof getChartSpec> = { groups: [] };
  let chartSpecError: string | null = null;
  try {
    chartSpec = getChartSpec({ headers: inlineTable.headers, rows: chartRows });
  } catch (err) {
    chartSpecError = err instanceof Error ? err.message : String(err);
    console.error('[chart] getChartSpec failed for topic', artifact.topic, err);
  }
  // An edit the user already made to this message's chart (type, measure,
  // row count) wins over the freshly-recomputed default -- otherwise every
  // render would silently discard whatever the user picked.
  const effectiveChartSpec = chartSpecOverride ?? chartSpec;

  const rows = inlineTable.rows;
  const totalRows = rows.length;
  const PREVIEW_ROW_COUNT = 8;
  // A large result (thousands of customer rows, say) should never force
  // React to mount that many <tr> elements just because a chart is open --
  // only the preview rows render in the DOM until the user actually asks
  // to see the rest.
  const visibleRows = tableExpanded ? rows : rows.slice(0, PREVIEW_ROW_COUNT);
  const isTruncated = !tableExpanded && totalRows > PREVIEW_ROW_COUNT;

  return (
    <section className="space-y-5 rounded-2xl border border-white/70 bg-white/90 p-6 shadow-[0_4px_14px_rgb(15_23_42/7%)] ring-1 ring-slate-950/5 backdrop-blur">
      <div className="flex items-center gap-2.5">
        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-teal-50 text-teal-600">
          <BarChart3 size={16} />
        </div>
        <p className="text-base font-semibold tracking-tight text-slate-900">{artifact.title}</p>
      </div>

      <div className="flex flex-wrap gap-2">
        {user ? (
          <Button
            size="sm"
            className="gap-2"
            disabled={reportSaveState === 'saving' || reportSaveState === 'saved'}
            onClick={onSave}
          >
            {reportSaveState === 'saved' ? <Check size={14} /> : <Save size={14} />}
            {reportSaveState === 'saving'
              ? 'Saving...'
              : reportSaveState === 'saved'
                ? 'Saved'
                : reportSaveState === 'error'
                  ? 'Save failed -- retry'
                  : 'Save Report'}
          </Button>
        ) : (
          <Link
            href="/login"
            className="inline-flex h-9 items-center justify-center rounded-lg bg-blue-600 px-3 text-sm font-medium text-white shadow-sm shadow-blue-600/20 transition hover:bg-blue-700"
          >
            Sign In To Save
          </Link>
        )}
        {user ? (
          <Link
            href="/reports"
            className="inline-flex h-9 items-center justify-center rounded-lg border border-slate-200 bg-white px-3 text-sm font-medium text-slate-700 shadow-sm transition hover:bg-slate-50"
          >
            Saved Reports
          </Link>
        ) : null}
        <Button variant="outline" size="sm" className="gap-2" onClick={onExport}>
          <FileSpreadsheet size={14} />
          Export Excel
        </Button>
      </div>
      {reportSaveState !== 'saved' ? (
        <p className="text-xs text-slate-400">This chart is not saved yet -- click Save Report to keep it.</p>
      ) : null}

      <div className="overflow-hidden rounded-xl border border-slate-200/80 bg-white">
        <div className="flex items-center justify-between border-b border-slate-100 bg-slate-50/60 px-4 py-2.5">
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">
            {totalRows
              ? `Table Preview (${visibleRows.length} of ${totalRows} row${totalRows === 1 ? '' : 's'})`
              : 'Table Preview'}
          </p>
          {isTruncated ? (
            <button type="button" onClick={onToggleExpand} className="text-xs font-semibold text-blue-600 hover:text-blue-700">
              View all {totalRows} rows
            </button>
          ) : tableExpanded && totalRows > PREVIEW_ROW_COUNT ? (
            <button type="button" onClick={onToggleExpand} className="text-xs font-semibold text-blue-600 hover:text-blue-700">
              Collapse
            </button>
          ) : null}
        </div>
        <div className="max-h-[360px] overflow-auto">
          <table className="w-full text-left text-sm">
            <thead className="sticky top-0 bg-slate-50 text-xs uppercase tracking-wider text-slate-500">
              <tr>
                {inlineTable.headers.map((header, i) => (
                  <th key={`${header}-${i}`} className="px-4 py-2.5 font-semibold">{header}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {visibleRows.length ? (
                visibleRows.map((row, i) => (
                  <tr key={i} className="odd:bg-white even:bg-slate-50/40">
                    {row.map((cell, j) => (
                      <td key={j} className="px-4 py-2.5 text-slate-700">{cell}</td>
                    ))}
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={inlineTable.headers.length} className="px-4 py-6 text-center text-slate-400">
                    No data available for this view.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {chartSpecError ? (
        <div className="rounded-xl border border-rose-200 bg-rose-50/80 p-4">
          <div className="mb-1 flex items-center gap-2">
            <BarChart3 size={16} className="text-rose-500" />
            <p className="text-sm font-semibold text-rose-700">Chart failed to generate</p>
          </div>
          <p className="text-sm text-rose-600">{chartSpecError}</p>
          <p className="mt-1 text-xs text-rose-400">The table above is unaffected -- this only stopped the chart. Check the browser console for the full error.</p>
        </div>
      ) : effectiveChartSpec.groups.length > 0 ? (
        <div>
          <div className="mb-3 flex items-center gap-2.5">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-teal-50 text-teal-600">
              <BarChart3 size={16} />
            </div>
            <p className="text-base font-semibold tracking-tight text-slate-900">{artifact.title} -- Chart</p>
          </div>
          <AutoReportChart
            table={{ headers: inlineTable.headers, rows: chartRows }}
            spec={effectiveChartSpec}
            onSpecChange={onSpecChange}
          />
        </div>
      ) : null}
    </section>
  );
}
